### ISSUE TITLE
Store screenshots in the repository

### ISSUE THREAD

**Issue by lassoan** [rbumm/SlicerLungCTAnalyzer#12]
Instead of storing screenshots as issue attachments, they could be stored in a folder (e.g., Docs), because they are not too big.
If there are more or larger screenshots then they can be uploaded as a release asset (create a release called DocsResources and upload the screenshots there).

But at least #1, #2, #3 issues should be closed so that they do not pollute the issue tracker.

**Comment by rbumm** [comment]
Ok, how do I link to the screenshots in the readme then?

**Comment by lassoan** [comment]
If you store images as release assets then you use absolute URLs. If you store them in the repository then you use relative path, for example `![](SomeScreenshot.png)` or `![](Docs/SomeScreenshot.png)`.

**Comment by lassoan** [comment]
You can also upload the test data as release asset. Github servers are very fast, reliable, and download speeds are good from anywhere in the world.

**Comment by rbumm** [comment]
There is an upload size limit to github - what is the recommended way to upload larger files ?

**Comment by lassoan** [comment]
As far as I know, the a 50MB soft limit and 100MB hard limit only applies to uploading files into the git repository. Do not upload anything big like that there! Screenshots may be OK, as they are only a few hundred KB, but any thing larger would make the repository bloated.

You can upload big files (I think up to 2GB as release assets). Create a new "TestingData" release [here](https://github.com/rbumm/SlicerLungCTAnalyzer/releases) and upload test data files by drag-and-drop. If you want to store screenshots as release assets, too, then probably it is cleaner to create separate "DocsResources" release; or keep everything in a release with a generic name, such as "Resources".

**Comment by rbumm** [comment]
Thanks Andras, will try that. Good morning from Switzerland.
