### ISSUE TITLE
Emphysema not detected in some cases 

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#19]
In some cases of a serial COVID-19 evaluation, "Emphysema right" and "Emphysema left" was not detected when HU of the areas was below -1000. 

The low value of the min threshold was adapted to -1050 for testing. 

@lassoan  what would be the recommended way to automatically detect lowest voxel intensity in a CT volume so maybe min threshold is not needed ?

**Comment by lassoan** [comment]
You can get minimum value of a volume by calling `volumeNode.GetImageData().GetScalarRange()[0]` (maximum is `volumeNode.GetImageData().GetScalarRange()[1]`).

**Comment by rbumm** [comment]
Thanks, works well, implemented ...

**Comment by rbumm** [comment]
Thanks, works well, implemented ...
