### ISSUE TITLE
Which kernel do we use ?

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#21]
Writing an abstract my radiologist coauthor asked, which kernel we use for our calculations. @lassoan  Will gladly name you as a coathor on following abstracts and papers. Can the we specify, which kernel we used in CTLA or can we change the kernel if needed? Thank you

**Comment by lassoan** [comment]
I'm not sure what kernel you mean. For which operation?

**Comment by rbumm** [comment]
My radiologist spoke about the fact that her emphysema judgement was "affected by the type of kernel" she used. 

In 3D slicer, I saw the possibility to select a "kernel" in the chest imaging platform under -> airway segmentation. Concerning Lung CT Analyzer - I am not sure how to answer her.

**Comment by lassoan** [comment]
Probably by "kernel" your radiologist means which interpolation or additional filtering method is used.

By default, Slicer uses bilinear interpolation for computing displayed pixels from voxels of the CT volume (with a few lines of Python script we can also switch to bicubic or sinc interpolation). Additional image processing filters are available in Simple Filters and other modules.

If your radiologist does not like the simple bilinear interpolation display and has some time to look at various interpolation options then I can provide Python code snippets that can switch between the different options. Note that resolution and color reproduction capabilities of the display may matter, too, so most likely a random laptop will not be able to show as nice images as displays in a radiologist reading room.

**Comment by rbumm** [comment]
Hi Andras, hope you are well. 

I have a short question concerning the DICOM networking problem I asked in the forum. 

I would not want to push that question in the forum up again, but I could do so, if you advise me to do so. 

My proplem is: Your python script example works with the public DICOM server you provided, but does not work within the hospital setting. It returns a "failed" operation upon retrieving the images. Query seems to work fine. 

All parameters are set exactly as I would do in the DICOM networking widget. 

Is it possible that the function

**Comment by lassoan** [comment]
Since MoveDestinationAETitle is a Qt object property, it can be read and written as `dicomRetrieve.moveDestinationAETitle`. It would be better to continue this discussion in that discourse thread because others will find that topic in the future and may need this information.
