### ISSUE TITLE
Suggestions for region statistics ? 

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#22]
Dear @lassoan I need a little push into the right direction.  

There is good overall progress with both Segmenter and Analyzer, but I am missing the possibility to calculate the extent of  "infiltrated" and "collapsed" regions of the lungs dorsally versus ventrally (and in apical, middle, and lower third). All this would be an awesome parameter for the need of putting patients supine vs. prone during ventilation. 

My first idea was to cut the lung masks into the respective pieces with the "surface cut" method. 

I already realized the calculation of the centroids (thanks for your code in the repository) in the right and left lung masks. Works great. I could easily define the plane for a mask "surface cut" from here. 

However, if I do this, I will be missing out on the few millimeters of "cut out" lung mask during the final Lung CT Analyzer processing. 

Alternatively, I could divide the result segments of Lung CT Analyzer into pieces, but I dont want to loose "material" of the segments. 

As an example I would need:

Infiltrated left lung  
Infiltrated left upper third  
Infiltrated left middle third  
Infiltrated left lower third  
Infiltrated left ventral half  
Infiltrated left dorsal half  
.  
.

Do you have any suggestions here?  
Maybe also a topic for Discourse if you think so.

**Comment by lassoan** [comment]
You can create mask segments (left,  left upper third, left middle third, left lower third, left ventral half, left dorsal half) and either combine with segments (infiltrated, etc) using Logical operators effect.

You can also experiment with Segment cross-section area module, which provides you a curve of how the area of a cross-section of a segment changes along a chosen axis. By dividing area of infiltration by total area, you could get percentage of infiltration along AP, IS, LR axes. You could get volumes in a region (e.g., upper third) by summing the values in a range and multiplying it with voxel height.
