### ISSUE TITLE
How to update Sampledata file

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#23]
Hi @lassoan , hope you are well. 

Before publiching a new program version of CT Lung Analyzer I would need to update the LungCTAnalyzerMaskSegmentation.seg.nrrd file on my server.

Tried to update both (file and SHA256.csv) with a new checksum, but Sampledata refuses to load the new segment file (expects a different checksum - the old one)

How should I proceed ? 

Thanks & regards

Rudolf

**Comment by lassoan** [comment]
You can find instruction for generating hash here:

https://github.com/Slicer/Slicer/blob/135f359dace2ad52f911604177dc064d7076da89/Utilities/Templates/Modules/Scripted/TemplateKey.py#L65-L66

I would recommend to host your data on github. It has a very fast and reliable worldwide content distribution system, that a privately hosted server cannot compete. You can upload binary assets on github for any release. I've created a "SampleData" release and you can upload data sets by [editing the release](https://github.com/rbumm/SlicerLungCTAnalyzer/releases/edit/SampleData) and drag-and-drop sample data sets to the "Attach binaries..." section.

**Comment by rbumm** [comment]
Thank you. I uploaded both files to 

[https://github.com/rbumm/SlicerLungCTAnalyzer/releases/tag/SampleData](https://github.com/rbumm/SlicerLungCTAnalyzer/releases/tag/SampleData)

the SHA hashes are

LungCTAnalyzerDemoCT.nrdd,9bb74f4383bce0ced80243916e785ce564cc2c8f535e8273da8a04f80dff4287  
LungCTAnalyzerMaskSegmentation.seg.nrrd,79f151b42cf999c1ecf13ee793da6cf649b54fe8634ec07723e4a1f44e53b57c

~How do I make 3D Slicer's Sampledata module know about the hashes ?~ 

~Do I need to implement the code you referred to in the first link (see above) into Lung CT Analyzer source code ?~

Found it.
