### ISSUE TITLE
CSV report file

### ISSUE THREAD

**Issue by romendacil64** [rbumm/SlicerLungCTAnalyzer#25]
Hey there,

I have very recently started using 3D slicer and the Lung Segmentation and Analyzer tool.

I am using nifti-files that for reasons of anonymity do not include metadata about the patient. Unfortunately, in such cases, the csv-report file created by the analyzer is only named with a timestamp - is there a way to change this to timestamp + filename?

Your tool is really fantastic and I am looking forward to work with it!

Best
Romendacil

**Comment by rbumm** [comment]
Thank you @romendacil64 , great that you like the tool. 

Which filename would you need to get included? 

Currently, there are two workarounds  - the easiest one maybe is to open the results folder via the "Open results folder" button directly after the CSV creation, sort the files by time created and add a prefix to the filenames. Secondly, you could call the logic of LungCTAnalyzer by script, this is quite complicated, though time-saving if you need to process a lot of files in a row. For that procedure, you would need to prepare the lung CT datasets including the lung masks, and define the thresholds before running the script.  

Best

Rudolf

**Comment by lassoan** [comment]
Another option would be to use the input volume node's name as report filename prefix if the volume is not loaded from DICOM.

**Comment by lassoan** [comment]
@romendacil64 note that nifti is not a general-purpose 3D image file format. It is developed for brain MRI images and should not be used for anything else because it is a very limited file format with many problems (different software interpret nifti files differently, which may cause mismatch in image orientation or may cause the image fail to load, and it has other disadvantages, such as non-human readable/editable/extensible file header). I would recommend to use nrrd file format instead.

**Comment by rbumm** [comment]
Yes, thanks, I just realized what @romendacil64 wanted. The input volume node name is not ideal because f.e. the public COVID CT dataset uses identical volume names (ct.nrrd) distributed to different foldes ("Pat 1","Pat 2","Pat 3" ...)

**Comment by rbumm** [comment]
But it is maybe better than just to use a timestamp in anonymized data ?

**Comment by rbumm** [comment]
Good news, input volume node name is now implemented as a prefix in the CSV report filename.   

@romendacil64 pls wait a few days until the extension manager offers the extension update.

**Comment by rbumm** [comment]
closed
