### ISSUE TITLE
4.13.xx preview:  LungCTSegmenter label texts missing and mask smoothing slower than previously

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#26]
When testing the LungCTSegmenter in Slicer 4.13.0-2021-08-05, placing the lung mask labels do not result in "R-1","R-2""R-3" labels as compared to the previous versions. The fiducials just show up as dots. 

When pressing "Apply", the generation of lung masks take longer than previously (127 \[4.13\] vs 56 s \[4.11\])

The "smoothing" part of the code takes longer (see statusMessages)

**Comment by lassoan** [comment]
> placing the lung mask labels do not result in "R-1","R-2""R-3" labels as compared to the previous versions

Point labels visibility is set from the defaults (that is saved in "Advanced" settings). We may change Slicer core to use different defaults for curves (where point labels are rarely useful) and points (where point labels are usually important), but for now you can turn on label visibility when the fiducial list is initialized to ensure that labels are always visible.

I would recommend to add a separate ticket for the slower speed. It would be useful to know exactly which step of the smoothing part takes more time.
