### ISSUE TITLE
Create compatibility between LungCTSegmenter and CIP

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#27]
I implemented the code in LungCTSegmenter  mentioned here

[https://discourse.slicer.org/t/exporting-csv-with-parenchyma-analysis-module/10697/17?u=rbumm](https://discourse.slicer.org/t/exporting-csv-with-parenchyma-analysis-module/10697/17?u=rbumm)

but this

![image](https://aws1.discourse-cdn.com/standard17/uploads/slicer/original/2X/a/a4bcef1500c54fa3c4fa175c37c7d85e79b4471e.png)

was produced leaving the labelmap input to "None". 

If I do a LungCTSegmenter run with the latest code and do this

![](https://user-images.githubusercontent.com/18140094/128834443-38f0520a-d77f-415c-8d20-f59b1d45439d.png)

I get this Lung segmentation-label. 

![](https://user-images.githubusercontent.com/18140094/128834627-4e273f23-31a8-4eb7-9784-5473368a9bc6.png)

the CIP-color tabe seems to have been generated: 

![image](https://user-images.githubusercontent.com/18140094/128835894-242d6e71-13f0-4535-ae85-086e11b3d5c6.png)

Feeding this to CIP and "Parenchyma Analysis" 

![](https://user-images.githubusercontent.com/18140094/128835036-6f4a6995-cb9b-4784-bb97-8e92a58ece95.png)

still results in

![](https://user-images.githubusercontent.com/18140094/128834904-0a9c5304-2cc2-47a4-9ee9-ae2a88453b2b.png)

**Comment by lassoan** [comment]
Have you chosen the generated color table for exporting the segmentation to labelmap (the color table specifies the label values for each segment)?

Do the label values for left lung, right lung, ... in the labelmap volume exported from segmentation match the label values for the same structures created by Parenchyma analysis?

**Comment by rbumm** [comment]
I am sorry, this got out of my focus for a while ... 
Yes, I have chosen the color table for exporting the segmentation to the labelmap. 
It seems to correctly translate the labels into WholeLung, RightLung and LeftLung with correct colors
However, the LeftLung histogram stays flat although the left lung mask is ok

![image](https://user-images.githubusercontent.com/18140094/130351397-dab610bb-5a89-4fe2-8ded-3061317c11df.png)

**Comment by rbumm** [comment]
> Have you chosen the generated color table for exporting the segmentation to labelmap (the color table specifies the label values for each segment)?

see above
 
> Do the label values for left lung, right lung, ... in the labelmap volume exported from segmentation match the label values for the same structures created by Parenchyma analysis?

label values = markup text  ("WholeLung","RightLung","LeftLung")? Yes they do

**Comment by rbumm** [comment]
V 2.44 now creates compatibility by letting the LungCTSegmenter writing out a label map with CIP conventions.
