### ISSUE TITLE
HowTo describe the technique of LCTA best in a paper's method section 

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#28]
@lassoan 

would

CT datasets were imported into 3D Slicer (1,2) and lung masks were semi-automatically segmented by Slicers' LungCTSegmenter (3)  extension by manually placing six fiducial markups (three axial, three coronal)  in the right and the left lung as well as one the trachea, setting a threshold mask (-3000/ -250 HU)  and involving the  "Grow From Seeds" operation of Slicers' segment editor. All lung masks were controlled visually and in a few cases (n=x), slight corrections were manually done by either using the "Scissors" tool (cut away a part of the mask) of the segment editor or its "Fill Between Slices" tool (adding a missing part to the lung mask) until the masks were perfect.  The 3D Slicer LungCTAnalyzer extension (3)  was then used to quantify "emphysematous", "inflated", "infiltrated", and "collapsed" lung in milliliters. Additionally, intrapulmonary vessels were segmented and subtracted from the beforementioned lung segments. There was no compensation for intrapulmonary bronchi. LungCTAnalyzer's program logic utilizes the "Threshold" tool of the "Segment Editor" and used the following threshold ranges:  xxxx This step is fully automatic. 

(1) The reference paper 

(2) Slicer 4.13: link

(3) LungCTAnalyzer extension: link 

be appropriate?

Pls advise if this is better answered in the forum

**Comment by rbumm** [comment]
Any recommendation on how to best notate the threshold range data in the text? (-1500 to -950) ?

**Comment by rbumm** [comment]
Do you think it is allowed or common practice to put a well-formulated method section on this Github (wiki) so other authors could use it?

**Comment by lassoan** [comment]
A few recommended simplifications:

CT datasets were imported into 3D Slicer (1,2) and lung masks were automatically segmented by LungCTSegmenter (3)  extension using 13 manually marked points. Three points were placed in axial and coronal views inside the right and the left lung, and one points in the trachea. The segmentation algorithm uses grow-cut algorithm with intensity region restricted to -3000 to -250 HU. All lung masks were verified visually and in a few cases (n=x), slight corrections were manually done by either using the "Scissors" (cut away a part of the mask) or "Fill Between Slices" (adding a missing part to the lung mask) tool in the of the segment editor.  The 3D Slicer LungCTAnalyzer extension (3) was then used to quantify "emphysematous", "inflated", "infiltrated", and "collapsed" lung in milliliters. Additionally, intrapulmonary vessels were segmented and subtracted from the beforementioned lung segments. There was no compensation for intrapulmonary bronchi.

I don't understand this last sentence:

> LungCTAnalyzer's program logic utilizes the "Threshold" tool of the "Segment Editor" and used the following threshold ranges:  xxxx This step is fully automatic. 

Automatic thresholding is an elementary operation (similar to addition, subtraction, multiplication), so if it is done automatically then you can just say that a certain structure was segmented by thresholding using X to Y range (no need to tell how). If the user needs to do some thresholding manually then you can describe what tool was used for that.

> Any recommendation on how to best notate the threshold range data in the text? (-1500 to -950) ?

I don't see this threshold range in the text.

> Do you think it is allowed or common practice to put a well-formulated method section on this Github (wiki) so other authors could use it?

Yes, absolutely. For example, you can add a "Use cases" section and such workflows in subsections.

**Comment by rbumm** [comment]
Great, thank you. 

> Automatic thresholding is an elementary operation (similar to addition, subtraction, multiplication), so if it is done automatically then you can just say that a certain structure was segmented by thresholding using X to Y range (no need to tell how). If the user needs to do some thresholding manually then you can describe what tool was used for that.

Ok I see.  

> I don't see this threshold range in the text.

It would be -1500 to -950, could I put it in brackets like this : (-1500 to -950) ?

> Yes, absolutely. For example, you can add a "Use cases" section and such workflows in subsections.

Ok, will do so.

**Comment by rbumm** [comment]
I a just working on the manuscript of the Palestinians who did a nice COVID-related study using LCTA. Would you want to become another coauthor here?

**Comment by lassoan** [comment]
`(-1500; -950)` or `[-1500; -950]` is more of a mathematical notation. Writing `from -1550 to -950` or `between -1550 and -950` or separating with [en dash](https://www.thepunctuationguide.com/en-dash.html) would be more common. However, in this case the en dash (`-1550 – -950') would be hard to read because of the negative sign. See some more details here: https://www.dailywritingtips.com/how-to-write-about-ranges/

**Comment by rbumm** [comment]
Went over to the Wiki. Thank you.
