### ISSUE TITLE
Markup error in Lung CT Segmenter 

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#29]
Slicer preview 4.13.0-2021-09-28

Error in Lung CT Segmenter concerning markup placement: 

The green slice constantly switches back to the red slice after adding the 7th marker.

**Comment by lassoan** [comment]
I've already fixed this (this is the problem I wrote about in the CIP pull request). Update your Slicer to the latest Slicer Preview Release.
