### ISSUE TITLE
Lung CT Segmenter throws exception in Slicer 5.1.0 revision 31036 built 2022-06-20

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#33]
![image](https://user-images.githubusercontent.com/18140094/174590130-ab83e033-27ff-4d98-90ba-fa6982a2b04e.png)

**Comment by rbumm** [comment]
Seems to be caused by  [https://github.com/rbumm/SlicerLungCTAnalyzer/blob/8ebb089513a01b2209b2ccb19fd01473cda095cd/LungCTSegmenter/LungCTSegmenter.py#L403](https://github.com/rbumm/SlicerLungCTAnalyzer/blob/8ebb089513a01b2209b2ccb19fd01473cda095cd/LungCTSegmenter/LungCTSegmenter.py#L403)

@lassoan it would be great if you could check the issue in the light of the upcoming ML workshop - is this a problem of Slicer preview or the extension?

**Comment by lassoan** [comment]
I just had a quick look and seems that [this line](https://github.com/rbumm/SlicerLungCTAnalyzer/blob/8ebb089513a01b2209b2ccb19fd01473cda095cd/LungCTSegmenter/LungCTSegmenter.py#L402) was incorrect. It should be changed to `if oldFiducial:`

@rbumm Could you please check if this change fixes the problem?

**Comment by rbumm** [comment]
Thank you @lassoan. 
Had tried that already, and this fixes the exception.
However, using Lung CT Segmenter, then Lung CT Analyzer, and then going back to the segmenter displays: 

![image](https://user-images.githubusercontent.com/18140094/174610611-a1538fbf-f410-4f03-bb63-ed938d14310f.png)

**Comment by rbumm** [comment]
As it fixes the exception, I´m closing this issue and will observe the warnings. Thank you!
