### ISSUE TITLE
How to remove the lobes from the segmentation results

### ISSUE THREAD

**Issue by ekmungi** [rbumm/SlicerLungCTAnalyzer#34]
Hi,

Firstly, thank you for sharing this amazing tool. I was using this for some Lung airway segmentation. However, I am not able to extract / export only the airway. The lung lobes also get automatically segmented as shown in the picture below. Is there a way I can export only the airway into a nrrd or a vtk file? Thank you.

![image](https://user-images.githubusercontent.com/406091/176243632-cd2c6eef-aca1-4e02-b6a2-343ebd28d424.png)

**Comment by rbumm** [comment]
Hi @ekmungi , 

Glad you like the extension. 

What you are showing in your image is the preview of the segmentation. 

Do these steps first, 

![](https://user-images.githubusercontent.com/18140094/176254448-37f5dd0c-359f-4720-a7a4-74fc91ad91e2.png)

then press Apply. 

You should get lungs and airways, something like 

![](https://user-images.githubusercontent.com/18140094/176254574-66067ecc-66e4-4e82-a86e-98f635ca402b.png)

Then go to "Data" module and unselect "right lung" and "left lung" (the "eyes" should be checked off) just to see the airways:

![](https://user-images.githubusercontent.com/18140094/176255208-1aa3bba0-f1d3-4894-b6a7-ffe4e20f879f.png)

Most of the time you need to do a little fine-tuning afterward.

If you do not need the lung segments right-click them and "Delete" 

Then "Save" 

![](https://user-images.githubusercontent.com/18140094/176255408-f7888504-2d02-4a0c-9eb8-633a64736c94.png)

**Comment by rbumm** [comment]
Maybe consider asking this question again in Slicer Forum, so I will answer it there too, may be helpful for other users...

**Comment by ekmungi** [comment]
Thank you @rbumm, I have moved the question to the slicer forum at https://discourse.slicer.org/t/how-to-get-airways-using-lungctanalyzer/24102
