### ISSUE TITLE
slicer.util.loadSegmentation creates inputVolume copy

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#35]
in line

https://github.com/rbumm/SlicerLungCTAnalyzer/blob/e79e188524fcd6530db0d3bb1dde6de93da99e8e/LungCTSegmenter/LungCTSegmenter.py#L1596

is there any way to avoid this ?

**Comment by lassoan** [comment]
I don't see any volume copying around there. Could you provide a bit more details?

**Comment by rbumm** [comment]
Can not reproduce it any longer :-) Sry
