### ISSUE TITLE
AI segmentation error: No module named 'torch'

### ISSUE THREAD

**Issue by MMdeB** [rbumm/SlicerLungCTAnalyzer#37]
When trying to use the Lung CT Segmenter extension with the use of AI (lungmask), I get the error that 'No module named 'torch'' is present. I have already downloaded the PyTorch extension in 3D slicer, but this wouldn't solve the problem. I use the 3D Slicer 5.1.0 version.  Could someone help me to solve this problem?

**Comment by rbumm** [comment]
Could you please ask this question in the support section of [Slicer discourse](https://discourse.slicer.org/)? I will try to answer it there and close the issue here later.  

Thank you.

**Comment by rbumm** [comment]
Using WIndows 11 and Slicer 5.1.0, pressing "Install Pytorch" results in

![](https://user-images.githubusercontent.com/18140094/195345265-43c5e19c-4c71-4644-a2a7-886ccf074f5d.png)

After that, "lungmask" AI works:

![](https://user-images.githubusercontent.com/18140094/195345802-b8dd9ab8-626e-4356-8856-45caa6e8ec4b.png)

**Comment by lassoan** [comment]
@rbumm If a module needs some dependencies then it must take care of installing those. Just before a module needs to use pytorch, the module can check if pytorch is available and if not then offer the user to install it by a single click. See a complete example here: https://github.com/lassoan/SlicerHDBrainExtraction/blob/c308995da9ded06c0833f8c3681e8202005db99d/HDBrainExtractionTool/HDBrainExtractionTool.py#L265-L272

**Comment by rbumm** [comment]
@lassoan thanks, very helpful, it was planned anyway and is now done. [6b56c9c](https://github.com/rbumm/SlicerLungCTAnalyzer/commit/6b56c9c99427d5d8a61b6195492ef3ad9414ce91)

**Comment by rbumm** [comment]
Too early. 

In an empty Slicer 5.1, [6b56c9c](https://github.com/rbumm/SlicerLungCTAnalyzer/commit/6b56c9c99427d5d8a61b6195492ef3ad9414ce91) throws:

![](https://user-images.githubusercontent.com/18140094/195362077-8a721f5c-749f-41d9-979c-2675837621db.png)

**Comment by lassoan** [comment]
First step is to check if SlicerPytorch is installed. For that you can do something like this: https://github.com/SlicerHeart/SlicerHeart/blob/42b75a6184b31d785eaef61ff695f4de99834356/BafflePlanner/BafflePlanner.py#L247-L248

If most users want to use AI and they have GPU then it may make sense to make SlicerPytorch extension as a dependency to LungCtAnalyzer extension. Then when the user installs LungCtAnalyzer, SlicerPytorch extension is installed automatically. It is a small scripted extension (does not actually install pytorch until it is requested), so it is probably OK to make it a dependency.

**Comment by MMdeB** [comment]
Hi, thank you for your answer. I installed Pytorch and I got further, but still an error occurs. First I got an error which I solved by installing Visual Studio, but now I still get an error:

`Failed to compute results: in method 'GetByteArrayFromImage', argument needs to be of type 'sitk::Image *'
Traceback (most recent call last):
  File "C:/Users/X/AppData/Local/NA-MIC/Slicer 5.1.0-2022-10-11/NA-MIC/Extensions-31192/LungCTAnalyzer/lib/Slicer-5.1/qt-scripted-modules/LungCTSegmenter.py", line 522, in onApplyButton
    self.logic.applySegmentation()
  File "C:/Users/X/AppData/Local/NA-MIC/Slicer 5.1.0-2022-10-11/NA-MIC/Extensions-31192/LungCTAnalyzer/lib/Slicer-5.1/qt-scripted-modules/LungCTSegmenter.py", line 1499, in applySegmentation
    segmentation_np = mask.apply(inputVolumeSitk)  # default model is U-net(R231), output is numpy
  File "C:\Users\X\AppData\Local\NA-MIC\Slicer 5.1.0-2022-10-11\lib\Python\Lib\site-packages\lungmask\mask.py", line 31, in apply
    inimg_raw = sitk.GetArrayFromImage(image)
  File "C:\Users\X\AppData\Local\NA-MIC\Slicer 5.1.0-2022-10-11\lib\Python\Lib\site-packages\SimpleITK\extra.py", line 269, in GetArrayFromImage
    array_view = GetArrayViewFromImage(image)
  File "C:\Users\X\AppData\Local\NA-MIC\Slicer 5.1.0-2022-10-11\lib\Python\Lib\site-packages\SimpleITK\extra.py", line 255, in GetArrayViewFromImage
    image_memory_view = _GetMemoryViewFromImage(image)
TypeError: in method 'GetByteArrayFromImage', argument needs to be of type 'sitk::Image *'
`

Do you know how to solve this? Thanks in advance!

P.S. I opened a question on the slicer support discourse, but it is still pending.

**Comment by rbumm** [comment]
Hi, 

there seems to be an error in the Slicer 5.1 Preview release. 
See
https://discourse.slicer.org/t/sitkutils-pullvolumefromslicer-does-not-create-sitk-image-in-slicer-5-1/25669

Please use Slicer 5.0.3 stable, just tested a fresh install for you, worked fine.

>>First I got an error which I solved by installing Visual Studio

Could you describe this error or do you have a screenshot ?

>> I opened a question on the slicer support discourse, but it is still pending.

Registration pending?

**Comment by MMdeB** [comment]
Hi, we are now having two conversations on two different [media](https://discourse.slicer.org/t/ai-segmentation-with-lung-ct-analyzer-error/25678). 

> Please use Slicer 5.0.3 stable, just tested a fresh install for you, worked fine.

Thank you, this solved the issue. It is now working fine!

> Could you describe this error or do you have a screenshot ?

As I said in my other post, I got the error:
`Failed to compute results: Command ‘[‘C:/Users/mmdeboer/AppData/Local/NA-MIC/Slicer 5.0.3/bin/…/bin\PythonSlicer.EXE’, ‘-m’, ‘pip’, ‘install’, ‘git+https://github.com/JoHof/lungmask’]’ returned non-zero exit status 1.`
I don't know anymore what was the complete error in the Python interactor, but it came down to the fact that it could not install the fill-voids module since I didn't have Visual Studio C++ installed on my computer. 

> Registration pending?

My post had to be approved since I was new to the site, but as you know, it is now approved.

Thank you for your help!

**Comment by rbumm** [comment]
\>> Thank you, this solved the issue. It is now working fine!

Great. Does that mean that the question in Slicer discourse is now fully solved too? If yes please post a short message in that thread. 

Thank you.
