### ISSUE TITLE
Improve lung segmentation module

### ISSUE THREAD

**Issue by lassoan** [rbumm/SlicerLungCTAnalyzer#7]
I've tried how lung can be segmented quickly and robustly and found the following workflow works well for the lung cancer and covid cases that I tried. With automation, it should be possible to get the segmentation in 1 minute, including verification.

Manual steps:

**Video: https://youtu.be/v1-L_niLZxQ**

1. Resample image to 2mm voxel size to make segmentation faster and standardized: go to "Resample scalar volume" module, set Spacing = 2,2,2, Output volume = Create new, Apply
2. Create 3 segments, lung right, lung left, trachea, use terminology, adjust colors
3. Set intensity masking that includes most of the lungs, except vessels and some completely collapsed regions: click Threshold effect, set lower threshold to the minimum (around -1000), higher threshold to cover the lungs (around -500), click "Use for masking"
4. In coronal and axial views, paint long diagonal lines across the right and left lung left and paint on the trachea in the coronal view
5. Create complete segmentation from these seeds: click "Grow from seeds" effect, click "Initialize", click "Show 3D", add more seeds as needed (if some regions are missed), click "Apply"
6. Disable intensity masking to allow filling in vessels and collapsed regions: uncheck "Editable intensity range" in Masking section
7. Fill in vessels and collapsed regions: click Smoothing effect, choose Smoothing method = "Closing (fill holes)", Kernel size = 12mm, select right lung segment, click Apply, select left lung segment click Apply
8. Switch the segmentation's resolution to match the original chest CT: click Segment geometry button, choose the original CT as Source geometry, click OK
9. Smooth out edges at the final resolution: click Smoothing effect, choose Smoothing method = Gaussian, Kernel size = 2mm

All these steps can be performed fully automatically except except:
- Step 4: paint seeds
- Step 5: verify segmentation and add more seeds as needed

It might be possible that the masking intensity range may need to be adjusted on a patient for each patient, but it is not likely (and it is just about moving a slider anyway).

If you can verify that this workflow works for all cases then I can help with automating the steps.

**Comment by rbumm** [comment]
The mask is definitively better than the one I create with https://github.com/rbumm/SlicerLungMaskGenerator . 
Solves the trachea problem. 
I will check the severe patient data and report back.

**Comment by rbumm** [comment]
Would I go from  https://github.com/rbumm/SlicerLungMaskGenerator for the implementation, create a pull request here,  or do I  need to start a new project from scratch? 
Guess that you also think it would be good to have two modules ...

**Comment by lassoan** [comment]
I would recommend to have all the modules in one extension, as they are closely related and they are developed, maintained, and used together.

**Comment by rbumm** [comment]
Ok, as soon as we have the mask implementation I will freeze my mask project.

**Comment by rbumm** [comment]
Andras, I  tested your algorithm with a severe case and it worked well. Can't show visual results here for obvious reasons. 
My only concern is that painting on the slices will make the whole procedure quite complicated. What I liked in my recent script was that I only needed to place four markers that were easy to memorize. But your new model with segmented trachea is definitely better, already thought about segmenting the trachea fully. In my tumor patients I always do the tracheal segmentation with "grow from seeds". Would suggest we go this way.

**Comment by lassoan** [comment]
The method is not sensitive to where the seeds are placed. Instead of painting, we can ask users to place a few markups points. From 3 points, we could generate the seeds automatically. This would be similar to how segmentation works in BreastImplantAnalyzer extension for implant segmentation.

Of course, we could even automate placement of those 3 points. But since you need to spend about a minute with reviewing the segmentation result anyway, saving a few seconds by automating placement of a few points may not worth the effort.

**Comment by lassoan** [comment]
So, the input for the lung segmentation module could be a threshold value (slider) and 3 point sets (one or more point for the right lung, left lung, and trachea). Whenever the threshold is moved or point is added/removed we could automatically perform steps 1-5 (once the image is resampled, this should not take more than a few seconds). When the user accepts the result, he would click a button and we would perform steps 6-9.

**Comment by rbumm** [comment]
That sounds very good - I will think about a possible realization but implementation will probably take me a week ... 
Would need to know how to present a modal dialog box in which the user is asked to do something ... Tried to look that up last week but did not find anything. Seemed from the comments that you do not like those dialogs in scripts ?   Need to read into the "new" sources as well ...

**Comment by rbumm** [comment]
I am a bit lost here. Do not want to touch the good working and optimized code / GUI of the analyzer, at best I would normally try implementing your mask segmentation suggestion in the other extension for testing. Partly because I would fear the necessity of having to push an urgent update of the Analyzer but being stuck in the middle of mask implementation.  I am sure you noticed already that I am probably a better surgeon than a programmer. What should I do?

**Comment by lassoan** [comment]
If you want to be completely safe then you can add the segmentation module to this repository in a subdirectory but not add that subdirectory to the CMakeLists.txt file [here](https://github.com/rbumm/SlicerLungCTAnalyzer/blob/master/CMakeLists.txt#L22). This way, anything you do in that folder will be ignored for now and  cannot break the extension.

**Comment by rbumm** [comment]
I actually went the safe way and implemented your suggestions into the Lung CT  Mask generator first. 
It actually works quite well and better than that what I had before. 
 
https://www.youtube.com/watch?v=FrUc3npvYag&feature=youtu.be

**Comment by lassoan** [comment]
This looks great!!
Have you pushed your latest changes to github?
If you are not sure how to add it to https://github.com/rbumm/SlicerLungCTAnalyzer extension then you can just push it to https://github.com/rbumm/SlicerLungMaskGenerator and I can merge it for you.

**Comment by rbumm** [comment]
Thanks, I pushed the latest changes now. Would be great if you could help to merge it with the analyzer ... With 2x2x2 the masks look a bit clumsy?

**Comment by lassoan** [comment]
Great! I'll make some fixes (add the missing step of switching to original image resolution before final smoothing) and send a pull request soon.
