### ISSUE TITLE
Rename repository to SlicerLungCTAnalyzer

### ISSUE THREAD

**Issue by lassoan** [rbumm/SlicerLungCTAnalyzer#8]
To have consistent naming across everywhere, it would be great if you could rename the repository to SlicerLungCTAnalyzer. I could take care of the rest (update the CMakeLists.txt files, folder names, Slicer extensions index, etc.).

**Comment by rbumm** [comment]
Done and thanks for taking care of the rest, would probably have made mistakes here.

**Comment by lassoan** [comment]
This is completed.
